services:
  serverside:
    build: ./serverside-dockerfile
#    ports:
#      - "3000:8000"
    command: python3 -m http.server 80
    networks:
      router-server:
        ipv4_address: 10.1.0.2
    cap_add:
      - NET_ADMIN

  clientside:
    build: ./clientside-dockerfile
    stdin_open: true
    tty: true
    networks:
      router-client:
        #        ipv4_address: 10.2.0.2
    cap_add:
      - NET_ADMIN

  router:
    build: ./router-dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      router-client:
        ipv4_address: 10.2.0.3
      router-server:
        ipv4_address: 10.1.0.3
    cap_add:
      - NET_ADMIN

  dnsserver:
    build: ./dnsserver-dockerfile
    stdin_open: true
    tty: true
    networks:
      router-client:
        ipv4_address: 10.2.0.4
    cap_add:
      - NET_ADMIN

  dhcpserver:
    build: ./dhcpserver-dockerfile
    stdin_open: true
    tty: true
    networks:
      router-client:
        ipv4_address: 10.2.0.5
    cap_add:
      - NET_ADMIN

networks:
  router-client:
    driver: macvlan
    ipam:
      config:
        - subnet: 10.2.0.0/16
          gateway: 10.2.0.1
  router-server:
    driver: macvlan
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
