FROM ubuntu:latest
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y nano
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install -y wget
RUN apt-get install -y iputils-ping
RUN apt-get install -y tcpdump
RUN apt-get install -y isc-dhcp-server
